### ISSUE TITLE
Getting MSAL token not working on Windows Server 2016

### ISSUE THREAD

**Issue by halatovic** [GruberMarkus/Set-OutlookSignatures#85]
Hello Markus,

we have deployed your script in organisation and it works fine on Windows 10/11 computers running Outlook. However, the organisation has RDSH terminal server running Windows Server 2016 and script is not working on the server. It throws error: Get-MsalToken : An error occurred while sending the request. I have checked and tried all troubleshooting hints given in error message but issue remains. Furthermore, I did script run on other servers running Windows Server 2016 and it throws same error. I have tried script on Windows Server 2019 machines and it worked fine just like on Windows 10/11 machines. 

Best Regards

Haris Alatovic

**Comment by GruberMarkus** [comment]
Hi @halatovic,

Please run the script with the '-verbose' parameter and provide the full output as text file.

**Comment by halatovic** [comment]
Hello Markus,

I have attached output.txt file. In addition I have noticed that on Windows Server 2016 machine default browser does not start and no O365 authentication happen.

Best Regards

Haris
________________________________

**Comment by GruberMarkus** [comment]
Please submit the log again, as GitHub does not seem to allow attachments sent via e-mail.

**Comment by halatovic** [comment]
[output.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/12441617/output.txt)
I have attached output.txt via browser.

**Comment by halatovic** [comment]
I have reopened the issue.

**Comment by GruberMarkus** [comment]
I will need some time to test this. In the meantime, please try the following:
- Win+R ("Run" in Explorer), cmd /k start http://localhost
  The default browser should start. If the browser brings an error message, it should not be about localhost being blocked, but rather that localhost can not be reached because there is no webserver hosting a page on this address
- Does it work when you use Set-OutlookSignatures v4.2.1?
  For a test run, it is not neccessary to go through the changelog from 3.6.1 to 4.2.1.

**Comment by GruberMarkus** [comment]
I can now reproduce the problem with v3.6.1 and v4.2.1 on Windows Server 2016.

It seems that the root cause is not in Set-OutlookSignatures or in one of its dependencies, but in the .Net Framework and PowerShell configuration of Windows Server 2016: Only TLS 1.0 is enabled by default, and that's not enough for Graph authentication.

Before running Set-OutlookSignatures, run the following code to temporarily enable all available security protocols in the current PowerShell session:
```
Write-Host "Active PowerShell Transport Layer Security Protocols: " -NoNewLine
[Net.ServicePointManager]::SecurityProtocol

Write-Host "Activate all PowerShell Transport Layer Security Protocols"
[enum]::GetNames([Net.SecurityProtocolType]) | foreach {
	try {
		[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol, $_
	} catch {
	}
}

Write-Host "Active PowerShell Transport Layer Security Protocols: " -NoNewLine
[Net.ServicePointManager]::SecurityProtocol
```

The change is only temporary and limited to the current PowerShell session.

If you want to make the change permanent, the registry key described in https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls#schusestrongcrypto might be a solution.


Please let me know if this solves your problem.

**Comment by halatovic** [comment]
Hello Markus,

your solution resolved the issue, thank you.

Best Regards

Haris Alatovic
