### ISSUE TITLE
[Reference Link] Support article link not working 

### ISSUE THREAD

**Issue by nitishkanu820** [GruberMarkus/Set-OutlookSignatures#9]
Hi,

You included one support link for reference but that link is not working.

Link : https://support.microsoft.com/kb/224663

**Comment by GruberMarkus** [comment]
The original link is indeed https://support.microsoft.com/kb/224663, but it seems to work only sometimes. I guess that's due to Microsoft's changes in the structure of their support site - sometimes it feels like multiple teams independently work on the modifications without knowing of each other...

Anyhow, the Internet Archive Wayback Machine hosts an old snapshot of the article: https://web.archive.org/web/20180827213151/https://support.microsoft.com/en-us/help/224663/document-file-size-increases-with-emf-png-gif-or-jpeg-graphics-in-word

The script will include the updated link in the next release.

**Comment by GruberMarkus** [comment]
Fixed in commit e485405.
The first release to contain this commit will be 2.0.2, which will be released in a few minutes.
